info:
    component: VR API
    project:
        name: VR-API
        version: 0.0.1-SNAPSHOT

server:
    port: 8080
    contextPath: /vr/
    tomcat:
        basedir: /tmp/tomcat

management:
    security:
        enabled: false

spring:
    application:
        name: VR-API
        h2:
            console:
                path: /h2

    jackson:
        default-property-inclusion: non_null

    jpa:
        show-sql: true
        format-sql: true
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create

    logging:
    level:
        org:
            hibernate:
                type: trace

    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:vr
        username: sa
        password: sa

        tomcat:
            max-wait: 60000
            initial-size: 10
            max-active: 150
            test-on-borrow: true